webapp:
  name: #APP_NAME
  group: #APP_NAME
  replicaCount: 1
  path: #URL_PATH
  tls:
    fqdn: #FQDN
    secretName: incommon-cert-#HOST
  container: 
    image: #WEBAPP_IMAGE
    imagePullPolicy: Always
    port: #WEBAPP_PORT
    memory: 1G
    cpu: 2
scheduler:
  name: scheduler
  path: /dask-dashboard
  container: 
    image: #DASK_IMAGE
    imagePullPolicy: Always
    dashboardPort: 8787
    workerPort: 8786
    memory: 1G
    cpu: 2
worker:
  name: dask-worker
  replicaCount: #WORKER_COUNT