apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.scheduler.name }}
    group: {{ .Values.webapp.group }}
spec:
  ports:
    - name: {{ .Values.scheduler.name }}
      port: {{ .Values.scheduler.container.workerPort }}
      protocol: TCP
    - name: {{ .Values.scheduler.name }}-webui
      port: {{ .Values.scheduler.container.dashboardPort }}
      protocol: TCP
  selector:
    app: {{ .Values.scheduler.name }}